import { type FileSystemItem } from '../file-system-map';
import {
  ITEMS_MAP_DOCUMENTS,
  ITEMS_MAP_FAVORITES,
  ITEMS_MAP_FITERMAN,
  ITEMS_MAP_IMAGES,
  ITEMS_MAP_LIBS,
  ITEMS_MAP_PROJETO_1_CHALLENGELETT,
  ITEMS_MAP_PROJETOS,
  ITEMS_MAP_ROOT,
  ITEMS_MAP_USERS,
  ITEMS_MAP_VIDEOS,
  ITEMS_MAP_WORKSPACE,
} from './';

export const STRUCTURE_MAP_FILE_SYSTEM: Record<string, FileSystemItem[]> = {
  // ROOT LEVEL 0 [ DRIVE ROOT C: ]
  'C:': Object.values(ITEMS_MAP_ROOT),

  // ROOT LEVEL 2 [ USUÁRIOS ]
  'C:/USUARIOS': Object.values(ITEMS_MAP_USERS),

  'C:/ARQUIVOS_DE_PROGRAMAS': [],

  // ROOT LEVEL 2 [ FITERMAN ]
  'C:/USUARIOS/FITERMAN': Object.values(ITEMS_MAP_FITERMAN),

  // ROOT LEVEL 3 [ FAVORITOS ]
  'C:/USUARIOS/FITERMAN/FAVORITOS': ITEMS_MAP_FAVORITES,

  // ROOT LEVEL 3 [ AREA_DE_TRABALHO ]
  'C:/USUARIOS/FITERMAN/AREA_DE_TRABALHO': ITEMS_MAP_WORKSPACE,

  // ROOT LEVEL 3 [ BIBLIOTECAS ]
  'C:/USUARIOS/FITERMAN/BIBLIOTECAS': ITEMS_MAP_LIBS,

  // ROOT LEVEL 3 [ COMPUTADOR ]
  'C:/USUARIOS/FITERMAN/COMPUTADOR': [],

  // ROOT LEVEL 3 [ DOCUMENTOS ]
  'C:/USUARIOS/FITERMAN/DOCUMENTOS': Object.values(ITEMS_MAP_DOCUMENTS),

  // ROOT LEVEL 3 [ DOWNLOADS ]
  'C:/USUARIOS/FITERMAN/DOWNLOADS': [],

  // ROOT LEVEL 3 [ IMAGENS ]
  'C:/USUARIOS/FITERMAN/IMAGENS': Object.values(ITEMS_MAP_IMAGES),

  // ROOT LEVEL 3 [ MÚSICAS ]
  'C:/USUARIOS/FITERMAN/MÚSICAS': [],

  // ROOT LEVEL 3 [ PROJETOS ]
  'C:/USUARIOS/FITERMAN/PROJETOS': Object.values(ITEMS_MAP_PROJETOS),

  // ROOT LEVEL 3 [ VIDEOS ]
  'C:/USUARIOS/FITERMAN/VIDEOS': Object.values(ITEMS_MAP_VIDEOS),

  // ROOT LEVEL 4 [ PROJETOS/CHALLENGE_LETT ]
  'C:/USUARIOS/FITERMAN/PROJETOS/CHALLENGELETT': Object.values(ITEMS_MAP_PROJETO_1_CHALLENGELETT),
};
