import { type FileSystemItem } from '../file-system-map';
import { ITEMS_MAP_FAVORITES, ITEMS_MAP_WORKSPACE, ITEMS_MAP_LIBS } from './';

export const STRUCTURE_MAP_SIDE_MENU: Record<string, FileSystemItem[]> = {
  'C:/USUARIOS/FITERMAN/FAVORITOS': ITEMS_MAP_FAVORITES,

  'C:/USUARIOS/FITERMAN/AREA_DE_TRABALHO': ITEMS_MAP_WORKSPACE,

  'C:/USUARIOS/FITERMAN/BIBLIOTECAS': ITEMS_MAP_LIBS,

  'C:/USUARIOS/FITERMAN/COMPUTADOR': [],
};
