import { type FileSystemItem } from '../file-system-map';
import { ITEMS_MAP_ALL } from './all-items';

export const ITEMS_MAP_WORKSPACE: FileSystemItem[] = [
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SOBRE_MIM'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS/BACKLOG.MD'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS/SETEJANELAS/ABOUT.MD'],
];
