import { type FileSystemItem } from '../file-system-map';
import { ITEMS_MAP_ALL } from './all-items';

export const ITEMS_MAP_WORKSPACE: FileSystemItem[] = [
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/PRIMEIRO_DOCUMENTO.TXT'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS/SEGUNDO_DOCUMENTO.TXT'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/DOCUMENTOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/PROJETOS'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/IMAGENS/ALFACE.WEBP'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/IMAGENS/PAO_DE_QUEIJO.JPG'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/VIDEOS/AMOR_FATAL.MP4'],
  ITEMS_MAP_ALL['C:/USUARIOS/FITERMAN/VIDEOS/TEASER_TOPGUN.MP4'],
];
